# Usa una imagen base de Node.js
FROM node:14

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo de aplicación en el contenedor
COPY index.js .

# Expone el puerto 3000 (o el puerto que uses en tu aplicación)
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD ["node", "index.js"]
