apiVersion: apps/v1
kind: Deployment
metadata:
  name: suma-app
  labels:
    app: suma-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: suma-app
  template:
    metadata:
      labels:
        app: suma-app
    spec:
      containers:
      - name: suma-container
        image: node:latest
        ports:
        - containerPort: 3000
        volumeMounts:
          - mountPath: /app/index.js
            name: app-code
            subPath: index.js
        command: ["node", "/app/index.js"]
      volumes:
        - name: app-code
          configMap:
            name: app-code

