apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-with-two-containers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dual-container-app
  template:
    metadata:
      labels:
        app: dual-container-app
    spec:
      containers:
      - name: node-app
        image: lucasoli13/kc-cicd:latest
        ports:
        - containerPort: 3000
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
